### ISSUE TITLE
Isotope widget and PeakDetector should use the same filtering options

### ISSUE THREAD

**Issue by lparsons** [ElucidataInc/ElMaven#567] opened 2018-01-26 21:05 UTC
When bookmarking a peak group with many isotopic peaks, the intensities seem to be correctly reported in the Isotope widget, but sometimes they are inexplicably missing (set to 0) in the bookmarks table.

This is a MAJOR issue for our lab, and apparently, can be traced back to very old Maven code.

![image](https://user-images.githubusercontent.com/645128/35460645-b9145318-02b2-11e8-8cc2-f94c2800a47a.png)

**Comment by chubukov** [comment] 2018-01-26 21:15
@lparsons we used to run into things like this all the time. I haven't recently (i.e. I thought they got fixed), but maybe with different data you've dug up some old bugs again. I also don't rely on the isotope widget as much as you do.

Here are a couple of things I would check or that could be responsible:
- which one is "right"? If you load the EIC for the C13-6 child peak, do you see a peak that should have a non-zero intensity?
- there are a couple of filters in the main options that control whether a peak is considered a valid isotopic child. Those are "min isotope-parent correlation" and "isotope is within [X] scans of parent". (I don't believe the maximum error to natural abundance filter is used). @sahil21 can we check that these filters are being applied the same way in both the isotope widget and the bookmarking process?

**Comment by chubukov** [comment] 2018-01-26 21:21
@lparsons hmm, I take it back, it looks like %error to natural abundance actually is still being used. I always have mine at 100%. So maybe try changing that too?

**Comment by lparsons** [comment] 2018-01-29 21:05
@chubukov We don't really want to rely on the isotope widget, but in this case, it's making the issue somewhat clear. The isotope widget is "correct", in the sense that there should certainly be non-zero peaks for those samples.
![image](https://user-images.githubusercontent.com/645128/35534265-f9b9b5cc-050d-11e8-89e3-9b9ef162f3ac.png)

This is after setting the *Minimum Isotope-parent correlation* to `-1`, *Isotope is within [X] scans of parent* to `10`, the *Maximum %Error to Natural Abundance* to `100%`, and the *Min. Signal Baseline Difference* to `0.00`.

**Comment by lparsons** [comment] 2018-01-29 21:31
@shubhra-agrawal Just wanted to note, this is probably the top priority issue for us, since it completely disrupts the workflow for isotopically labeled samples and makes the data unreliable. If anyone has thoughts on where in the code to start looking, I'm happy to help with the debugging.

**Comment by lparsons** [comment] 2018-01-29 21:36
Here is one of the peaks showing that one sample is inexplicably not "selected". These unselected peaks correspond to the erroneous zero (0) values in the table.
![image](https://user-images.githubusercontent.com/645128/35535725-832f0fb0-0512-11e8-8ef3-d76aafd3cda1.png)

**Comment by chubukov** [comment] 2018-01-29 23:18
@lparsons looks so similar to #386 (which I do think we fixed). The first place I would start debugging would be to look to see if the correlation function is returning NaN for some reason.

**Comment by shubhra-agrawal** [comment] 2018-01-30 06:10
@lparsons Can you share this data with us along with the settings file? We can look for other datasets and reproduce this bug but I reckon it will be faster this way.

**Comment by lparsons** [comment] 2018-01-30 16:33
@shubhra-agrawal I'm working on getting permission to share the data. I'll update you as soon as I know. Thanks for looking into this!

**Comment by lparsons** [comment] 2018-01-30 16:43
@shubhra-agrawal I shared a Google Drive folder with you that contains the data we used to demonstrate this issue. Please let me know if you need anything else.

**Comment by shubhra-agrawal** [comment] 2018-01-31 07:33
@lparsons So I'm looking at the data in El-MAVEN. Neither of the widgets are showing wrong data per se. The F-1-1 peak is not included in the C13-label-1 group (you can tell because the peak is not highlighted when you click on C13-label-1 in the peak table) which is why you see zero intensity for that sample in the table. But that sample does have a C13-label-1 peak so it shows up in the isotope widget.

This is a grouping problem essentially. I don't see any obvious reason for that peak to not be included in the group. Need to debug it properly.

**Comment by shubhra-agrawal** [comment] 2018-01-31 10:59
@lparsons @chubukov Turns out, _Isotope is within [X] scans of parent_ is to blame for the grouping issue. When I leave other isotope detection settings to default and set this to 15 scans instead of 5, the F-1-1 peak is grouped as C13-label-1.

Grouping also happens on the fly when looking at the EIC widget (this does not take isotope/non-isotope into consideration so isotopic settings do not apply) which is why you see all those peaks as one group when you hover over the F-1-1 peak. There have been a few discussions around making the EICs from peak table immutable but we have never really gotten around to working on it.

Have you seen any disparity between the isotope widget and peaks table apart from this example?

**Comment by chubukov** [comment] 2018-01-31 12:00
@shubhra-agrawal I'm not convinced it's a grouping issue per se. As far as I remember, there's no additional grouping that happens on the isotopic children -- they are pulled separately for each sample and directly assigned to the peakgroup. Is that not true?

It does sure look to me like the peak that's missing is the left-most one, so @lparsons is it possible that you're really just hitting the left edge of the "isotope within x scans of parent" window? Values in the 5-15 range work well in my experience for QE data where the scan speed isn't that high. I can't tell for sure, but you may have slightly higher scan speed, so you may want to up the window?

Either way there still seems to be a bug with the isotope widget using a different value of the parameter than the peak updater.

**Comment by chubukov** [comment] 2018-01-31 12:25
@shubhra-agrawal actually another thing that might have helped in this case is using the spline peak instead of the highest intensity scan for the peak position (#464).

**Comment by shubhra-agrawal** [comment] 2018-02-01 07:30
@chubukov Correct. By grouping issue, I meant that it was not at all obvious why that peak is not included in the group. Also, it looks to me like that set of peaks is included in 2 groups? One that includes the F-1-1 peak and one that does not. I might be missing something though.

Isotopes widget and PeakDetector have a lot of duplicated code for isotope detection. Looks like the isotope widget is not using parent-isotope correlation (and therefore scanDiff). I'm assuming this is because isotopes widget is written for a more group-agnostic formula-based search? It's taking the current scan and looking for highest isotopic intensity in a particular sample. While Parent-isotope correlation in this case can be calculated using the expected Parent m/z instead of mean m/z of the parent group (like it happens in peak table), we're not sure if that is ideal as the values might still be different in the two widgets. @chubukov thoughts?

In any case, @sahil21 has been looking into refactoring the isotope detection part to get rid of all duplicate code blocks. This will definitely help get rid of a lot of bugs in labeled data workflows.

**Comment by shubhra-agrawal** [comment] 2018-02-01 07:34
@lparsons Let me know if you have seen any data mismatch between the two widgets apart from this example?

**Comment by chubukov** [comment] 2018-02-01 12:46
@shubhra-agrawal I think both the widget and the peak detector should respect the maxScanDiff and minCorrelation parameters. The point of those parameters is to try to distinguish an isotope from another spurious peak.

The way the peakDetector isotope code works is that it takes the EIC for the isotope m/z window, and tries to find the closest peak to the parent RT. If that peak is within the maxScanDiff window, then it's assigned as a child peak. There is also the check on the correlation of intensities across the entire +/ maxScanDiff window (probably this should be changed to be across the peak bounds?). So no grouping is done for the child peaks -- as long as the parents are grouped, they will always get grouped as well. And also no grouping when you click on the group in the peak table. So the way that an isotope doesn't get included like this is if there's just no peak found in within the RT window or if it fails one of those checks.

**Comment by lparsons** [comment] 2018-02-01 16:55
@shubhra-agrawal This is a very commonly seen problem in the lab and occurs many times for many compounds in the sample data I sent.

@chubukov Let me know if there is anything else I can do to help trouble shoot (or fix?) this issue, or if you have ideas for a workaround in the meantime. Thanks so much for looking into it.

**Comment by chubukov** [comment] 2018-02-01 17:12
@lparsons did raising the maxIsotopeScanDiff solve it?

what scan rate (scans/second) is your data acquired at?

**Comment by lparsons** [comment] 2018-02-01 17:18
@chubukov Yes, it seems that increasing the *Isotope is withing [X] scans of parent* to 15 resolved the issue for this peak. Progress! This at least gives us a workaround. Still seems like the disconnect between the bookmarks and the isotopes widget is problematic, and perhaps some of the logic for isotope detection should be changed. Seems like we should either refine this issue or create a new one.

@lichenpu Could you answer @chubukov question about what scan rate (scans/second) this data was acquired at?

**Comment by LiChenPU** [comment] 2018-02-01 17:23
@chubukov Thanks! The scan rate is 2 scans/second.

**Comment by chubukov** [comment] 2018-02-01 17:23
@lichenpu @lparsons only reason i ask is to try to help you estimate what a reasonable number would be for maxIsotopeScanDiff. You can of course just judge this empirically

I think we all (@shubhra-agrawal ?) agree that we should change the isotope widget to use the same filtering (maxIsotopeScanDiff and correlation) as the peak detector.

**Comment by chubukov** [comment] 2018-02-01 17:27
Ok, ours is close to 3-4/s and we typically use a value of 15 for maxIsotopeScanDiff. Perhaps in this particular peak you just have a shift. Also if it's a noisy peak then #464 becomes important.

**Comment by lparsons** [comment] 2018-02-01 17:48
@chubukov Thanks again, I'm updating our internal documentation to reflect this.

@chubukov @shubhra-agrawal I propose we update the title of this issue to reflect the desire to change the isotope widget to use the same filtering (maxIsotopeScanDiff and correlation) as the peak detector.

**Comment by shubhra-agrawal** [comment] 2018-04-13 08:56
@lparsons @chubukov We did some refactoring to remove duplicated code snippets between the Peak detection and isotope widget. The v0.3.0 beta release shows consistent intensity values for labels. 

Changes in this release:
- Consistent values between peak table and isotope widget
- Less clutter in the widget (only non-zero labels)
- Click on a compound from the compound widget to look at label intensities. (provided a group is highlighted in the eic widget)
- Sample drop-down has been added to the isotope widget.
- Clicking on isotopic children in the peak table shows label intensities for the parent group. Not random values.

Note: I have identified a couple of crash-points that will hopefully be resolved before the official release. 
- Deleting a sample while using the isotope widget. Un-checking a sample works fine.
- Moving too fast between peak table and compound widget

Let me know if there are any other issues/comments.

**Comment by shefalilathwal** [comment] 2018-04-13 10:04
@shubhra-agrawal I am facing the same issue with isotope detection. Relaxing the minimum parent isotope correlation and number of scans in the Windows version 0.2.4-73 resolves the problem, but the parameters do not seem to have any effect in Mac v0.2.4-38 and the problem persists.

**Comment by shubhra-agrawal** [comment] 2018-04-13 11:26
@shefalilathwal The version number tells you how many commits ahead the application is with respect to the last release. In this case, the Windows version is 73 commits ahead of v0.2.4 whereas the Mac version is 38 commits ahead of 0.2.4. Which is why, it works in the first one. v0.3.0 beta is out now. We'll send the official v0.3.0 release version to you soon.

With your particular dataset, there was an issue with the scan difference between parent and child peak (around 13 scans). @Raghavdata suggested relaxing the min. parent-isotope correlation to -0.6 which seems to work for now. 

As a permanent fix for this, we are thinking of implementing (#575 ). Essentially, the problem is that El-MAVEN goes by scan number when looking for labeled peaks. It assumes a window of 2-4 scans will be enough RT difference to find labeled peaks; which is not a fair assumption to make, considering the scan rates can be very different for different machines. Instead, user should put in the max RT difference which should be used for this. Thoughts?

**Comment by shefalilathwal** [comment] 2018-04-13 11:37
@shubhra-agrawal makes sense. Just wanted to point out that in version 0.2.4-38, relaxing the parameters doesn't work in case anyone else is seeing this issue.

**Comment by shefalilathwal** [comment] 2018-04-13 15:07
@chubukov, under normal circumstances you would be right. But I am looking at isotopic standards so I know it's the right isotopic peak. One issue in these data is the peak shape which is not perfectly smooth, so the 'peak' for isotope can be some scans away, though not as much as 13, but definitely more than 2 or 3. The negative correlation again seems to be a workaround to get maven to pick the right group. At this point I do not understand how correlation is being used and why making it negative leads to picking the right group. I believe that's something the team needs to look at.

**Comment by chubukov** [comment] 2018-04-19 01:08
@shefalilathwal I find this type of correlation to be one of the most useful metrics in Maven. It's basically the correlation of intensities between the two EICs, across the scans across the peak. If your two peaks are coming from species with the same chemical properties (isotopes, adducts, fragments) you would expect the correlation to be quite high.

**Comment by shubhra-agrawal** [comment] 2018-04-23 14:41
@shefalilathwal Let's test your data on v0.3.0 and file a separate issue if necessary.

@lparsons @chubukov I'm closing this issue as it seems to be working fine during beta testing. As a next step, we'll implement #575.

**Closed by shubhra-agrawal** 2018-04-23 14:41 UTC
Labels: bug, core
