### ISSUE TITLE
multithreading and static variables

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#412] opened 2017-09-28 14:29 UTC
I haven't seen anything to indicate that my hypothesis regarding issue #388 is incorrect -- that the problem was caused by using static local variables in a multithreading environment.

There are dozens of other places where static local variables are used in key calculation functions. Most of them will probably be fine (and may well help a lot with performance), but I believe we should go through them carefully and see if there are places where this would cause issues.

**Comment by sahil21** [comment] 2017-10-06 14:32
@chubukov I was looking at issues #333 #388 #334 and I can confirm that it is indeed multithreading issue. I tried disabling multithreading and couldn't reproduce those issues. I can't confirm right now whether it is the problem with static variables. But using static variables in multithreading environment is not a good idea.

**Comment by chubukov** [comment] 2017-10-06 15:00
@sahil21 great, agreed. I haven't see exactly the issues I described ever since I put in that fix to get rid of the static declaration. But I have a suspicion my last comment here in #334 might have something to do wit h something similar, and maybe also the discussion we've been having about the distX/distY weight sliders being screwy.

**Comment by saifulbkhan** [comment] 2020-07-08 11:06
All issues linked here have long been resolved. Closing this. Feel free to open if something similar comes up again.

**Closed by saifulbkhan** 2020-07-08 11:06 UTC
Labels: c++, high, optimization
