### ISSUE TITLE
Maven crashed when tried to upload certain files

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#461] opened 2017-11-15 00:30 UTC
Files have been shared with @sahil21 I uploaded the files to El Maven but before the upload process could complete El Maven crashed. I tried a few times with the same outcome.

#El_Maven v0.2.1 windows

**Comment by shubhra-agrawal** [comment] 2017-11-15 06:42
@raaisakuk We traced the segmentation fault back to the SRM list widget. I looked at your sample files while debugging and there's data missing for a particular filterline (index=449) in all the files. Is that by design?

In any case, it makes sense to handle this event while reading in the scans. Scans with no data should just be skipped. Do you, as a user, want to be notified when a scan is skipped because of missing data?

**Comment by raaisakuk** [comment] 2017-11-15 16:57
@shubhra-agrawal Hey, thanks for looking into this. This comment is going to be long, sorry for that.

I am not exactly sure what you mean by "filterline" here. Could you explain that? 
I did find index=449 in .mzML file and if I understand correctly the tag <binary></binary> was empty.  As these files go through a conversion from .D Agilent Chemstation, I tried tracing back to it. So, I first convert .D files into .mgf using openchrome and then to .mzML/.mzXML using MSConvert. I could find that in .mgf also this particular (it was scan 450 in mgf) scan was empty. As .D is a proprietary format I couldn't trace back anything after that so I don't really understand what the scan here means. 

If this helps, the group running the GCMS is using SIM mode which actually finds only the given ions and not the Scan mode where you give a range of masses. (more about it [here](https://www.eurofinsus.com/environment-testing/our-company/newsletters/gcms-sim-vs-scan-mode/))

You can get more details about the type of process, raw files etc from @gbutrico. (Please add her to the user list if you can) She is the one who does the GCMS part of the experiment and would be able to explain things better.

**Comment by shubhra-agrawal** [comment] 2017-11-16 07:38
@raaisakuk @gbutrico  So I read about SIM and looked at the files again. There is an m/z array and a corresponding intensity array for every run. Both these arrays are empty for index=449 so it was basically an empty run. We already handle the case of empty runs in mzXML format so it shouldn't be too difficult to do it for mzML as well. 

I doubt the user would want a notification for skipped runs but correct me if you see a use case for it.  

"Filterline" is just how we refer to the run ID, sorry for not making it clear. This is the ID displayed in the SRM widget. For some data, it conveys information like precursor/product m/z pair tracked in that run, etc but in this case it looks auto-generated and serialized. Which is fine.

**Comment by raaisakuk** [comment] 2017-11-16 14:44
@shubhra-agrawal Seeing your comment about mzXML format, I converted the files into mzXML and uploaded to ElMaven. It doesn't crash but I get an empty EIC. 

![image](https://user-images.githubusercontent.com/33527542/32896970-677cf8b2-cab2-11e7-89a2-edb3b01ae10e.png)

Ya, I don't think the user will be interested in knowing empty runs as long as things work. @gbutrico What do you think?

**Comment by gbutrico** [comment] 2017-11-16 14:50
@raaisakuk @shubhra-agrawal Thanks for looking into this. Just so I am understanding, this index happened to contain no data for the m/z array it was scanning? Are there multiple instances of this within each index, or is this the only one? I just want to make sure this isn't a bug that has lost data, and that it's truly just an empty run. Especially since it occurs in every file, and there were several different methods/measurements represented in this dataset.

**Comment by shubhra-agrawal** [comment] 2017-11-16 15:07
@gbutrico I checked a few files at random. This is the only index that has no m/z array or intensity array data in every one of those files. You can verify this by searching for an empty binary tag in the mzML or mzXML files. It will look like this: `<binary></binary>`

@raaisakuk I'll take a look.

**Comment by raaisakuk** [comment] 2017-11-17 15:27
@shubhra-agrawal We also found the same thing that this particular index has data in <binary></binary>. @gbutrico and I looked at the file together before replying to your first comment. 
What we are not sure about is if this happens for all files and is there any other index with no runs or only this one?

**Comment by shubhra-agrawal** [comment] 2017-11-20 13:50
@raaisakuk The mzXML files have msLevel=2 which signifies MS/MS data even though this is not an MS/MS data set. Looks like there is a conversion issue here from .D to .mzXML format. I'll look into alternatives and let you know.

Every file that I checked in your data set had an empty binary tag for index=449. There are no other empty indices in any of the files I checked, just index=449.

**Closed** 2019-07-29 06:29 UTC
Labels: bug, confirmed
