### ISSUE TITLE
Y-axis scaling

### ISSUE THREAD

**Issue by collinhill** [ElucidataInc/ElMaven#205] opened 2017-04-10 20:36 UTC
As displayed below, ElMaven has some issue with y-axis scaling

![maven scaling](https://cloud.githubusercontent.com/assets/26555162/24881419/b2b5ff12-1e0b-11e7-801a-5dbc304f12b0.png)

**Comment by GeorgeSabu** [comment] 2017-04-11 15:57
@collinhill Thanks for reporting. This issue is a duplicate of #135. We are working on it and it will be resolved in the coming release.

**Comment by sahil21** [comment] 2017-10-24 06:25
@collinhill Closing this one. Duplicate of issue #135

**Closed by sahil21** 2017-10-24 06:25 UTC
