### ISSUE TITLE
look into mass slicing

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#152] opened 2017-02-28 00:42 UTC
It happens all the time that the result of untargeted peak detection includes a bunch of peaks that overlap absolutely perfectly in m/z - rt space. 

I would like to try to understand why this happens and if it could be improved.

**Comment by chubukov** [comment] 2017-02-28 00:48
Assigning to myself for now, but happy to have anyone look into it.

**Comment by r-el-maya** [comment] 2017-06-23 12:32
@chubukov 
   
-  First we will go through the algorithm with the help of code documentation.
-  Check for overlapping of the mass slices.
-  If such a probability should exist, will have to modify the algo accordingly.

**Comment by chubukov** [comment] 2017-06-27 23:07
@r-el-maya @sahil21 one additional question on this: am I right that the "Auto-detect and ignore isotopes" radio button does absolutely nothing?

**Comment by sahil21** [comment] 2017-06-28 11:12
@chubukov Yes, it is not being used anywhere. This option was not part of Maven build 769 so it came in between 769 and 775.

**Comment by r-el-maya** [comment] 2017-07-14 15:57
@chubukov  Replying to https://github.com/ElucidataInc/ElMaven/commit/6b12810eaa5cd838619d065fccb759ca576943e8#commitcomment-23020303

Yes, this function is called after creating the slices. Currently, we are not changing the way how the slices are being created. Though we know how and why the overlapping(sometimes 100%) occurs, we can’t avoid overlaps just by changing some parts of the algorithm.

The reason behind that being, while iterating over samples and in turn scans, for each observation, we are creating slices, if there is no already existing slice in the range ‘mz-mztolerance’ to ‘mz+mztolerance’. This case doesn’t create any problem. But, if there already exists any such slice, we merge this new one with the existing one, expanding the original one. This expansion when done iteratively, creates problem causing huge percentage of overlaps.

Overlaps are indeed necessary to facilitate the range(mz & rt) broad enough to have all the data of a particulate peakgroup in one slice. But we only have 
Problem when the overlap is more than some extent.

This implementation is just a temporary fix. We are thinking of a new algorithm that will avoid such unnecessary overlaps.

**Comment by chubukov** [comment] 2017-07-14 16:07
@r-el-maya Thanks very much for the more detailed explanation. I'm still not sure I fully understand (when it merges two slices, does it not eliminate one of them?). But I think your approach of a temporary fix that simply detects hugely overlapping slices is totally reasonable.

More than one PhD thesis can be (and probably has been) devoted to properly solving this problem. Maven's approach has always been a very hacky one, which had the advantage of producing a reasonable result very quickly. If we implement something new (if we do that, I would encourage borrowing from some of the other freely available tools), let's consider the tradeoffs together.

Thanks for the work on this.

**Comment by mayankmtg** [comment] 2018-06-12 04:36
@chubukov @shubhra-agrawal @sahil21 The problem supposedly present in Mass Slicing Algorithm is where we update the slices if a slice already exists. The merge procedure is not that direct. Merging of two slices means updating the already inserted one according to the new slice What might happen after regular update of slices that are close is that they increase in size and might start overlapping. Since a slice is just a template on which peak detection takes place, almost similar slices might logically report the same group. This can be reasoned for the occurrence of duplicates. Overlaps and duplicates are a classical problem of binning (mass slicing). There may be several approaches to solve this issue. One might be to use fixed sized bins along the mass axis, but the bin size will not always be the same for all data-sets. Creating a slice around each data-point in 3D domain, which is what El-Maven is doing, might actually handle variations across data-sets better. Another approach is to post-process the slices. But not incorporating peak information in the post-processing and removing duplicates only on the basis of slice area overlap might not robustly remove duplicates. We can however use a correlation based post-processing step. This means that we can cross correlate the reported groups, and remove the same ones. This incorporates data information as well and also removes duplicate groups, thus also removing the duplicate peaks.

**Comment by mayankmtg** [comment] 2018-06-12 05:03
Refer to Pull Request #730

**Comment by saifulbkhan** [comment] 2020-03-19 12:05
With our new approach (slicing -> merging -> adjusting), I have not run into any exact duplicates. Although, peak-groups sharing a large amount of common mz-rt space are still found. So, it is not as good as it can be, but we believe that the new method is more sensitive to slicing parameters and stable in terms of reproducibility (across sessions and machines).

Closing this, feel free to re-open if you run into any instances of this issue with v0.10.0 (and beyond).

**Closed by saifulbkhan** 2020-03-19 12:05 UTC
Labels: bug, core, discussion, low
