### ISSUE TITLE
Untargeted groups not obeying the ppm limit

### ISSUE THREAD

**Issue by shubhra-agrawal** [ElucidataInc/ElMaven#1242] opened 2020-02-27 06:48 UTC
**Describe the bug**

I'm running untargeted peak detection with 10ppm, 10 scans, 10000 min intensity for the MVH data (to be shared offline) on develop (a23027d5). Some of the peak groups have a higher ppm range than 10ppm and the peak bubbles are floating on the y-axis till the ppm sync is switched on. This was supposed to be resolved by the mass slicing changes, not sure how it came back.

**Comment by saifulbkhan** [comment] 2020-02-28 10:38
@shubhra-agrawal I get many thousands of groups with this dataset and exact parameters. But, I could not find any that had the bubble issue you describe. Although I did see it for myself, I am guessing it was some different build or the parameters somehow got changed. If possible, can you share the emDB file? Maybe then I would be able reproduce your issue.

**Comment by saifulbkhan** [comment] 2020-03-19 13:13
Closing this, since it was confirmed, on PR #1243, that the issue described here, is no longer happening.

**Closed by saifulbkhan** 2020-03-19 13:13 UTC
