### ISSUE TITLE
Source File column headers

### ISSUE THREAD

**Issue by MyaSteadman** [ElucidataInc/ElMaven#52] opened 2016-11-11 16:49 UTC
in EL Maven, the column headers must be the following in this order:
compound	expectedRt	id	formula	mz

the following columns in this order would not load into El Maven:
compound	formula	id	rt	mz

**Comment by chubukov** [comment] 2016-11-11 18:04
Both work fine in Maven 776 I believe. Probably related to changes made as a result of #2 ? 

It's ok if the source file format is more restrictive (though it would be nice if it's not), but let's document it clearly.

**Comment by GeorgeSabu** [comment] 2016-11-13 16:24
@MyaSteadman @chubukov There is no restriction in the order of the headers in the code. I rearranged the headers of a database and tried recreating this issue. But I was not able to reproduce this. Would it be possible to share the compound database with which I can reproduce the issue?

**Comment by chubukov** [comment] 2016-11-13 16:47
Is it "rt" vs expectedRt"?

**Comment by GeorgeSabu** [comment] 2016-11-14 01:46
@chubukov If both "rt" and "expectedRt" are present "rt" is chosen over "expectedRt". This behaviour is same in all versions of maven. I tried replacing "rt" with "expectedRt" in this header sequence "compound formula id rt mz" that also didn't give me the reported issue.

**Comment by chubukov** [comment] 2016-11-14 21:05
@MyaSteadman @GeorgeSabu  I also can't reproduce the problem. The file on xactive\\Data\test.tab has the headers you described and loads fine for me.

Why don't we have another look at the file that didn't work if you still have it. Otherwise let's close this for now.

**Comment by GeorgeSabu** [comment] 2016-11-28 05:53
@chubukov @MyaSteadman Can I close this issue?

**Comment by chubukov** [comment] 2016-11-28 14:53
Closing given inability to reproduce. @MyaSteadman if it happens again, let's have a closer look at both files.

**Closed by chubukov** 2016-11-28 14:53 UTC
Labels: bug
