### ISSUE TITLE
deleted groups still exported to json

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#394] opened 2017-09-23 04:54 UTC
Looks to me like when a group is deleted from a table, it still stays in `vallgroups` and is therefore exported when exporting to json.

I'm not sure I fully follow what the difference is meant to be between `allgroups` and `vallgroups`.

**Comment by rish9511** [comment] 2017-09-26 12:08
@chubukov 
It's similar to issue #261 
Deleted isotopes in the peaks table are not actually deleted from the corresponding Lists containing the isotopes, hence they get exported to csv, json

This might help us in solving #261 as well

**Comment by IpankajI** [comment] 2017-10-27 04:42
@chubukov It's been resolved and merged to develop.

**Comment by shubhra-agrawal** [comment] 2019-07-29 07:00
@chubukov Cannot reproduce this on current develop.

**Closed by shubhra-agrawal** 2019-07-29 07:00 UTC
Labels: bug, high
