### ISSUE TITLE
bookmarked peaks disappears

### ISSUE THREAD

**Issue by collinhill** [ElucidataInc/ElMaven#203] opened 2017-04-10 20:01 UTC
The bookmarked peaks window will disappear when you try to merge it with other widgets, i.e. merging it with the samples/compounds tabs.  The bookmarked peaks cannot be retrieved after this.  Oddly, it only happens with the bookmarked metabolites identified through the peak detection feature.

**Comment by GeorgeSabu** [comment] 2017-04-12 03:37
@collinhill This issue is there because peak tables are created dynamically after peak detection is done. This issue will be resolved in the coming release.

**Comment by chubukov** [comment] 2017-05-03 14:27
Just noting this is duplicate of #154.

**Comment by chubukov** [comment] 2017-07-19 22:01
I believe this is working fine now? -- maybe @sahil21 can confirm.

**Comment by sahil21** [comment] 2017-07-20 04:24
@chubukov @collinhill This is working in the current develop. I'm closing this issue.

**Closed by sahil21** 2017-07-20 04:25 UTC
Labels: bug, confirmed, medium, qt
