### ISSUE TITLE
Maven crashes when deleting entires in the Peaks table using the 'delete' key.

### ISSUE THREAD

**Issue by singleton-christopher** [ElucidataInc/ElMaven#242] opened 2017-05-10 17:55 UTC
When I generate a table of peaks using the 'Peaks' button (to select peaks using S/N ration over blanks), I tried to use the 'delete' key to remove entries.  Most every time I do this, Maven crashes.

**Comment by chubukov** [comment] 2017-05-11 18:21
Talked to Chris offline, noted that this is observed quite often (e.g. #148), suggested using good/bad more than deleting (and also that S/N ratio can be set in peak picking parameters).

@sahil21 is this fix mentioned in #148 merged into the current develop?

**Comment by singleton-christopher** [comment] 2017-05-11 19:49
Noted.  I do use the S/N when peak picking, but still go through the extracted peaks to check overall signal and peak shape.  I'll  stick with good/bad in the future.

**Comment by sahil21** [comment] 2017-05-12 05:06
@chubukov @singleton-christopher The fix for #148 is merged with the develop branch. Also, I'm not able to reproduce this crash with current develop. @singleton-christopher Could you please confirm the El-Maven version you are using? The version number is displayed on the top bar of the window (eg.  "El_Maven_v0.1.0-beta-38-g9e4c3a3").

**Closed** 2017-07-19 22:11 UTC
