### ISSUE TITLE
Isotopic barplot checkboxes are dependent on bookmark checkboxes

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#489] opened 2017-12-11 11:45 UTC
There is a dependency issue in checkboxes of Isotope Detection tab [Options Dialog]. Isotope barplot and isotope widget checkboxes are dependent on "Bookmark, peakdetection & export" checkboxes.

**Comment by shubhra-agrawal** [comment] 2019-05-23 06:38
Can't reproduce in v0.7.1-beta. Closing it.

**Closed by shubhra-agrawal** 2019-05-23 06:38 UTC
Labels: bug, confirmed, ui-ux
