### ISSUE TITLE
Save custom compound database

### ISSUE THREAD

**Issue by raaisakuk** [ElucidataInc/ElMaven#467] opened 2017-11-17 20:42 UTC
I have a compound database with custom retention times and annotations. It would be great if I can somehow save that and not load it everytime I start El Maven. I see a Save widget on the side but it's greyed out.

**Comment by chubukov** [comment] 2018-02-11 16:12
same as #568 ?

**Comment by raaisakuk** [comment] 2018-02-16 14:29
Not sure. I read that issue but couldn't understand the details.

**Comment by rish9511** [comment] 2018-02-16 17:22
@raaisakuk  @chubukov 

Yes, this is a problem as of now. It only remembers the path of Databases that are shipped along with it

and yes, #568 is same as this one hence marking this one as duplicate

**Comment by rish9511** [comment] 2018-02-16 17:24
Duplicate of #568

**Comment by raaisakuk** [comment] 2018-02-16 18:15
@rish9511 Should I close this issue then?

**Comment by rish9511** [comment] 2018-02-21 11:42
@raaisakuk 
Sorry, I misunderstood the issue. This one is not same as #568 

If I understand your issue correctly, then you would want to make changes to the uploaded databases (e.g Knows database) and have the functionality to save the changes made to it. Correct me if I am wrong

What database get's uploaded depends on what was being used when El-Maven was closed

**Comment by saifulbkhan** [comment] 2020-07-08 10:43
The original feature described here has long been supported through the "Library manager". Closing this now.

**Closed by saifulbkhan** 2020-07-08 10:43 UTC
Labels: feature
