### ISSUE TITLE
crash if integrating peak from formula

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#722] opened 2018-06-01 11:39 UTC
If I put a formula into the search box and then integrate the resulting peak, I get a crash.

I did send the crash reports yesterday. Were they useful in identifying this?

**Comment by chubukov** [comment] 2018-06-05 12:02
@rish9511 ok, I do customize our builds a little bit, so let's see what we can figure out in the future.

And let's resolve the underlying bug obviously -- it seems quite easily reproducible.

**Comment by rish9511** [comment] 2018-06-05 12:54
@chubukov 
sure

**Comment by sahil21** [comment] 2018-06-12 13:17
@chubukov I'm not able to reproduce this crash on current develop. Can you send us the commit id?

**Comment by chubukov** [comment] 2018-07-08 01:05
@sahil21 sorry I missed this. Did you have isotopes enabled? I think it's only in that case.

**Comment by chubukov** [comment] 2018-07-08 02:09
@sahil21 this appears to be fixed in the current version

**Comment by sahil21** [comment] 2018-07-09 11:56
@chubukov This might be the result of this commit https://github.com/ElucidataInc/ElMaven/commit/be89272fbe94e7becd7733778f6fdc7e1b7c90ff

Closing the issue.

**Closed by sahil21** 2018-07-09 11:56 UTC
