### ISSUE TITLE
Initialization problem in loading some data sets

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#431] opened 2017-10-12 06:17 UTC
The data doesn't load properly (EICs are empty) when loading the data just after re-compilation.

Steps to reproduce:
1. Recompile the application (uninstall and run)
2. Load dataset (have seen in data-dependent ms2. Not in ms datasets)
3. Try looking at the compounds from the compound database. EICs will be empty or very few intensity points.
4. Recomputing EICs fixes the problem.

**Comment by shubhra-agrawal** [comment] 2019-07-29 06:31
@sahil21 Can't reproduce in current develop. Closing the issue.

**Closed by shubhra-agrawal** 2019-07-29 06:31 UTC
Labels: bug, confirmed
