### ISSUE TITLE
El-Maven crashes when re-sorting files

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [ElucidataInc/ElMaven#937] opened 2018-12-11 16:35 UTC
**Describe the bug**
El-Maven is loading my files in backwards order:
File_12.mzML
File_11.mzML 
...
File_1.mzML

However, when I click on the down arrow to resort the files, El-Maven crashes. I have tried both version 0.5 and 0.4.1, and it happens in both.

**Expected behavior**
I expect El-Maven to sort files without crashing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9040216/49815018-cf236780-fd38-11e8-9a24-395b9390c025.png)

**System (please complete the following information):**
 - OS: Windos 7
 - Version v.0.4.1 and v.0.5

**Comment by shubhra-agrawal** [comment] 2018-12-12 09:03
@KujawinskiLaboratory Thanks for reporting the issue. 

We received a crash report at around the same time as this issue was created. It is from a Windows system and shows some activity in the alignment visualization plot. Did you have the widget open, by any chance? if this is reproducible, could you tell me the exact steps you follow? I've tried a few things on my end on Linux and Windows 10 machines to no effect.

**Comment by KujawinskiLaboratory** [comment] 2018-12-12 15:56
Interestingly, version 0.5 crashed, but there was no notice about a crash report. That came when I tried version 0.4.1.
Widget? I think I know what a widget is, but I am not clear on which widget I might have had open.
On Windows 7, here are the steps to recreate this:
open El-MAVEN (0.4.1 or 0.5)
Close the window that pops up offering help
Go to the File menu, select Load Samples (or click 'open' icon on toolbar)
Select set of files to open
(the files will load 'backwards' as in the picture I posted)
Click on the downward facing triangle on the menu bar above the word 'sample'
Crash, with menu that says 'ElMaven.exe has stopped working'

**Comment by shubhra-agrawal** [comment] 2018-12-12 16:07
I'll try this on my windows 7 system in an hour or two and let you know what I find. 

P. s. Apologies for not being clear. By 'widget' here, I meant the plot for alignment visualization. You can find its toggle button on the right hand panel (4th from the top). I was just curious if that was open. Not a problem if you don't remember.

**Comment by KujawinskiLaboratory** [comment] 2018-12-12 16:08
If the widget in question opens automatically when I start El-Maven, then it would be open. However, I did not open it up before opening the files.

**Comment by shubhra-agrawal** [comment] 2019-05-23 07:31
@KujawinskiLaboratory A couple of changes since the last update,
- El-MAVEN loads samples in the correct order (not backward)
- You can drag and drop the samples to reorder them
- Sorting is not available for sample widget anymore.

These changes are available as part of v0.7.1-beta. We will soon upload the final v0.7.1 installers on the website. Let us know if there are any concerns. Closing this thread till then.

**Closed by shubhra-agrawal** 2019-05-23 07:31 UTC

**Comment by chubukov** [comment] 2019-05-23 12:48
> * Sorting is not available for sample widget anymore.

Sorting was a nice feature, especially the sort by injection order!

**Comment by shubhra-agrawal** [comment] 2019-05-27 08:08
@chubukov I agree. Unfortunately, Qt seems to have an either/or situation when it comes to sorting and drag-and-drop. Since Rabinowitz lab and Calico both requested drag-and-drop, we have implemented that for now, but we are looking for a way to provide both features simultaneously.

**Comment by chubukov** [comment] 2019-08-13 13:54
@shubhra-agrawal being able to sort by sample order would really be good for us, and I imagine for a lot of people. Could we have a compile-time flag maybe?

**Comment by saifulbkhan** [comment] 2019-08-19 07:44
@chubukov With #1137, sample list widget will feature column-based sorting as well as rearrangement using drag-and-drop. It will be available with release v0.9.0.
