### ISSUE TITLE
Bug in RTdiff vs RT plot for all samples in loess fit alignment

### ISSUE THREAD

**Issue by Raghavdata** [ElucidataInc/ElMaven#312] opened 2017-08-08 12:43 UTC
The RTdiff vs RT plot for all samples in loess fit alignment is presently empty.  This needs to be fixed

**Comment by rish9511** [comment] 2017-09-11 13:08
@Raghavdata @sahil21  could you please test this out. If it's seems okay to you then I'll create  a PR

**Comment by rish9511** [comment] 2017-09-15 13:52
@sahil21  @Raghavdata 
Here is  a screen shot of Alignment Poly Dock Widget for loess fit
![screen shot 2017-09-14 at 2 49 12 pm](https://user-images.githubusercontent.com/10898272/30485450-0dc2a480-9a4b-11e7-82e1-7ed515234481.png)

**Comment by rish9511** [comment] 2017-09-19 11:33
@chubukov @sahil21 
Poly fit and loess fit use different parameters for generating x axis and y axis points.
For Loess fit:
* xAxis: original RT values (before running loess fit)
 * yAxis: difference between original RTs and updated RTs (after running loess fit)

**Comment by chubukov** [comment] 2017-09-20 01:08
@rish9511 It looks like the algorithm is not anchored to align the first and final timepoints to each other. I thought that most alignment algorithms imposed this constraint. What happens with the scans that get aligned to outside the original RT range? Is the entire range extended? Or do they simply disappear?

**Comment by sahil21** [comment] 2017-09-20 08:02
@rish9511 @Raghavdata I'm not sure we should use "difference between original RTs and updated RTs" for y-axis points. This information tells us how much the peaks have shifted but not how much the peaks are aligned. I think the difference between expected RTs and updated RTs makes more sense. Any thoughts @chubukov?

**Comment by chubukov** [comment] 2017-09-20 12:04
@Raghavdata @sahil21 The way that @rish9511 described it is the way I was imagining this plot. It's the way that xcms does it, and it basically tells you a) did the alignment do anything, b) were any of my samples particularly badly shifted c) was there a consistent trend in the shift over time

Sahil, what you're describing is basically your plot with the pink and grey rectangles, but centered on expectedRt for "known" compounds instead of being centered on originalRt, right?

**Comment by Raghavdata** [comment] 2017-09-21 05:53
@chubukov To answer your questions around the initial and final timepoints, the algorithm simply extrapolates the function it saw in the nearest fit to that point. It extrapolates the closest fit because loess fit is a part by part fit and unlike polynomial fit there isn't one polynomial function defining the RT shift in the whole sample.  Thus points which are defined outside the RT range are also taken into account and shift according to closest fit to them.

**Comment by chubukov** [comment] 2017-09-21 13:40
@Raghavdata so is the final result that the RT range may be expanded quite a bit, because a particular scan might get mapped by the regression function to an RT value outside the original range? Is this properly taken into account when creating the new EIC window? (I don't know at what point the RT range is calculated). Can a scan be mapped to an RT < 0? That would create some issues, I know there are various places where RT > 0 is assumed.

**Comment by Raghavdata** [comment] 2017-09-28 03:35
@chubukov As discussed on the call yesterday I will implement cutoffs at the edges as well as dummy points in the fitting function for the corners.

**Comment by chubukov** [comment] 2017-09-28 03:38
Sounds good. May be worth another careful look at how other programs do this.

**Comment by shubhra-agrawal** [comment] 2019-05-23 06:55
Loess fit has been marked as a deprecated feature and will soon be removed. Closing this.

**Closed by shubhra-agrawal** 2019-05-23 06:55 UTC
Labels: bug, fixed
