### ISSUE TITLE
Intensity values shown in EIC and exported in CSV do not match for Untargeted Analysis

### ISSUE THREAD

**Issue by VVinDevv** [ElucidataInc/ElMaven#1121] opened 2019-07-26 07:12 UTC
CSV export does not export intensity values according to the quantification type in some groups after performing automated feature detection. The intensity reported is always PeakAreaTop instead. One can compare intensity values in EIC plot and the values in CSV, to see the difference.

### Steps to reproduce the behaviour:
1. Set the following parameters for automated feature detection:
    - Set peak quantification type t o "Height".
    - mass domain resolution = 20 PPM
    - time domain resolution = 10 scans
    - limit intensity range = 10000
    - max intensity peak = 5000
    - min good peak group = 1 peaks
    - leave the rest as default
2. Perform automated feature detection.
3. Compare sample intensity values of features in exported CSV and its EIC, difference in values and does not match.

### Expected behavior
Intensity values in exported CSV should match what EIC plot shows.

### System information
 - OS: MacOS
 - Version 10.14.6

**Comment by saifulbkhan** [comment] 2019-07-26 11:57
Closing this, since we were unable to reproduce this on develop.

**Closed by saifulbkhan** 2019-07-26 11:57 UTC
