### ISSUE TITLE
grouping parameters affect mergedEIC?

### ISSUE THREAD

**Issue by chubukov** [ElucidataInc/ElMaven#333] opened 2017-08-16 17:42 UTC
I noted some odd behavior with the new grouping parameters in the last comments here: #151 

I observed something else funny: as I change the grouping parameters, the mergedEIC changes significantly. I don't fully understand why this happens because as far as I can tell the mergedEIC should jus be an average of the intensities of the EICs, having nothing to do with grouping.

**Comment by shubhra-agrawal** [comment] 2017-09-12 12:35
@chubukov We have not been able to reproduce this in v0.1.4 or v0.1.3. I tried unchecking 'Consider Overlap' and setting distX weight to 0 as suggested in #334. Could you post some screenshots and provide any other settings that might help us see this in effect?

**Comment by chubukov** [comment] 2017-09-26 17:59
@shubhra-agrawal I'm almost certain this had to do with #388

**Comment by sahil21** [comment] 2017-10-07 04:56
@chubukov I'm not able to reproduce this issue after removing the static variables in **gaussian1d_smoothing** function. I'll test other issues as well #334 #388

**Comment by sahil21** [comment] 2018-02-09 06:06
@chubukov Closing this one. Resolved with #412

**Closed by sahil21** 2018-02-09 06:06 UTC
Labels: bug, core, high
